(function (){
    //0-based indexed
    var selectedOption = [];

    //1-based indexed
    var currentQuestion = 1;

    var answered = 0, marked = 0;

    function getQuestions(){
        const questions = [
            {
                "id": 1,
                "question":"It's dark. You have ten grey socks and ten blue socks you want to put into pairs. All socks are exactly the same except for their colour. How many socks would you need to take with you to ensure you had at least a pair?",
                "options":[
                    {
                        "id":1,
                        "value":3
                    },
                    {
                        "id":2,
                        "value":16
                    },
                    {
                        "id":3,
                        "value":8
                    },
                    {
                        "id":4,
                        "value":7
                    }
                ],
                "answer":3
            },
            {
                "id": 2,
                "question":"A certain pet store sells only dogs and cats. In March, the store sold twice as many dogs as cats. In April, the store sold twice the number of dogs that it sold in March, and three times the number of cats that it sold in March. If the total number of pets the store sold in March and April combined was 500, how many dogs did the store sell in March?",
                "options":[
                    {
                        "id":1,
                        "value":80
                    },
                    {
                        "id":2,
                        "value":120
                    },
                    {
                        "id":3,
                        "value":160
                    },
                    {
                        "id":4,
                        "value":100
                    }
                ],
                "answer":100
            },
            {
                "id": 3,
                "question":"The revenue generated by Company X is divided between Doug and Moira in a 6 to 5 ratio respectively. \nA: Moira’s share when the revenue generated by Company X is $15,700 \nB: $7,900",
                "options":[
                    {
                        "id":1,
                        "value":"The quantity A is greater"
                    },
                    {
                        "id":2,
                        "value":"The quantity B is greater"
                    },
                    {
                        "id":3,
                        "value":"The two quantities are equal"
                    },
                    {
                        "id":4,
                        "value":"The relationship cannot be determined from the information given"
                    }
                ],
                "answer": "The quantity B is greater"
            }
        ]
        return questions;
    }

    function loadNavButtons(){
        for(let i=1; i<=questions.length;i++){
            var btn = document.createElement("BUTTON");
            btn.className = "quizNavQuestionSelector";
            btn.innerText = i;
            btn.onclick = function(){
                loadQuestion(i);
            };
            document.getElementById("quizNavQuestionSelectorBlock").appendChild(btn);
            selectedOption.push(null);
        }
    }

    function loadQuestion(number){
        document.getElementById("questionAndOptionsQuestionNumber").innerText = "Question " + number;
        document.getElementById("questionText").innerText = questions[number-1].question;
        for(let i=0; i < document.getElementsByClassName("questionAndOptionsOptionText").length;i++){
            document.getElementsByClassName("questionAndOptionsOptionText")[i].innerHTML = questions[number-1].options[i];
        }
        //change current question
        currentQuestion = number;

        var radioButton = document.getElementsByName("questionAndOptionsOptionSelectorGroup");
        for(var i=0;i<radioButton.length;i++){
            if(selectedOption[currentQuestion-1] === i){
                radioButton[i].checked = true;
            }
            else{
                radioButton[i].checked = false;
            }
        }
    }

    function setRadioButtonsMethod(){
        var radioButton = document.getElementsByName("questionAndOptionsOptionSelectorGroup");
        radioButton.forEach((e,index) => {
            e.onclick = function(){
                //check if question is marked for the first time
                if(selectedOption[currentQuestion-1]===null){
                    answered += 1;
                    loadSectionSummary();
                    //change color of the Question
                    document.getElementsByClassName("quizNavQuestionSelector")[currentQuestion-1].style.backgroundColor = "rgb(230, 248, 242)";
                    document.getElementsByClassName("quizNavQuestionSelector")[currentQuestion-1].style.color = "rgb(8, 189, 128)";
                }
                selectedOption[currentQuestion-1] = index;
            }
        })
    }

    function loadSectionSummary(){
        var summary = document.getElementsByClassName("quizNavSectionSummaryText");
        summary[0].innerHTML = answered + " answered";
        summary[1].innerHTML = marked + " marked";
        summary[2].innerHTML = (questions.length - answered) + " unanswered";
    }

    (function setupCountDown(){
        var countDownDate = new Date();
        countDownDate.setHours(countDownDate.getHours() + 3);
        countDownDate.setSeconds(countDownDate.getSeconds() + 2);
        var intervalOneSec = setInterval(function(){
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = countDownDate - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            document.getElementById("timerCountdown").innerHTML = ("0" + hours).slice(-2) + " : " + ("0" + minutes).slice(-2) + " : " + ("0" + seconds).slice(-2);
            if(distance < 0){
                clearInterval(intervalOneSec);
                //close the test after time after timer ends
            }
        },1000);
    })();

    (function handleBottomButtons(){
        var prevButton = document.getElementById("questionBottomButtonsPrevButton");
        prevButton.onclick = function(){
            if(currentQuestion > 1){
                currentQuestion-=1;
                loadQuestion(currentQuestion);
            }
        }

        var nextButton = document.getElementById("questionBottomButtonsNextButton");
        nextButton.onclick = function(){
            if(currentQuestion < questions.length){
                currentQuestion +=1;
                loadQuestion(currentQuestion);
            }
        }

        var markButton = document.getElementById("questionBottomButtonsMarkButton");
        markButton.onclick = function(){
            
        }
    })();

    const questions = getQuestions();
    loadQuestion(1);
    setRadioButtonsMethod();
    loadNavButtons();
    loadSectionSummary();
})();