function getQuestions(){
    const questions = [
        {
            "question":"It's dark. You have ten grey socks and ten blue socks you want to put into pairs. All socks are exactly the same except for their colour. How many socks would you need to take with you to ensure you had at least a pair?",
            "options":[3, 16, 8, 7],
            "answer":3
        },
        {
            "question":"A certain pet store sells only dogs and cats. In March, the store sold twice as many dogs as cats. In April, the store sold twice the number of dogs that it sold in March, and three times the number of cats that it sold in March. If the total number of pets the store sold in March and April combined was 500, how many dogs did the store sell in March?",
            "options":[80, 120, 160, 80],
            "answer":100
        },
        {
            "question":"The revenue generated by Company X is divided between Doug and Moira in a 6 to 5 ratio respectively. \nA: Moira’s share when the revenue generated by Company X is $15,700 \nB: $7,900",
            "options":["The quantity A is greater", "The quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given"],
            "answer": "The quantity B is greater"
        }
    ]
    return questions;
}

function loadNavButtons(){
    for(let i=1; i<=questions.length;i++){
        var btn = document.createElement("BUTTON");
        btn.className = "quizNavQuestionSelector";
        btn.innerText = i;
        btn.onclick = function(){
            loadQuestion(i);
        };
        document.getElementById("quizNavQuestionSelectorBlock").appendChild(btn);
    }
}

function loadQuestion(number){
    document.getElementById("questionAndOptionsQuestionNumber").innerText = "Question " + number;
    document.getElementById("questionText").innerText = questions[number-1].question;
    for(let i=0; i < document.getElementsByClassName("questionAndOptionsOptionText").length;i++){
        document.getElementsByClassName("questionAndOptionsOptionText")[i].innerHTML = questions[number-1].options[i];
    }
}

const questions = getQuestions();
loadQuestion(1);
loadNavButtons();